FROM nginx:latest

#RUN addgroup --gid 3000 --system app

#RUN adduser --uid 3000 --system --disabled-login --disabled-password --gid 3000 app

#COPY ./conf.d/brackets.conf /etc/nginx/conf.d/brackets.conf

COPY ./conf.d/ /etc/nginx/conf.d/