version: "3"

services:
    openvas:
        image: mikesplain/openvas
        ports:
          - 443:443
        environment: 
          PUBLIC_HOSTNAME: 161.35.122.179
        volumes:
          - ./data:/var/lib/openvas/mgr/